services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "6432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
