spring:

  application:
    name: "simplepos"

  datasource:
    url: "jdbc:postgresql://localhost:6432/postgres"
    username: "postgres"
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"